### ISSUE TITLE
Some analyses no longer work

### ISSUE THREAD

**Issue by romainbh** [sitn/SelvansGeo#35]
Both in Consultation and Edition mode, these following analyses no longer work with QGIS 3.16 (but do with 3.10):
- INVENTAIRES - Pourcentage de résineux
- INVENTAIRES - Volume de la tige moyenne
- INVENTAIRES - Pourcentage PMG
- INVENTAIRES - Répartition des espèces
- INVENTAIRES - Volume par hectare
- COUPES - Volume des coupes par année
- COUPES - Volume des coupes pour une période

**Comment by kalbermattenm** [comment]
I am trying to understand what is going wrong, but this is really not trivial....

**Comment by kalbermattenm** [comment]
Something is going wrong with the `addFeatures` method, which always returns false since QGIS 3.16 (https://github.com/sitn/SelvansGeo/blob/master/core/thematicanalysis.py#L385)

Maybe we should wait for a minor release to see if this is some kind of QGIS bug.
